---
title: "First Knit"
author: "Jayden Hudson"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
I attended Lancaster High School for 3 years and finished my last year of school at Pike High School, in Indianapolis. I graduated at Pike High. English has always been my favorite subject and easiest. Math takes me the longest to get through. I always did the best in my english class. Critical thinking and Literature are my strong suits.  
  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

I have a mac book which is owned by Apple. I would say im at a 7.5 when it comes to computers. I also have access to internet at home and it runs pretty strong. 
  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

My name is Jayden, but I don't mind being called Jay/ J. I wouldn't wan't anyone to call me anything other than my given name or Jay/ J.      
  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

I want to become a Psychologist for children. The course that im taking right now is what im most interested in. Im getting my associates at AVC but I want my Bachelors in Psychology. 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

I've been to canada. I've never been to the military but all the men in my life including my dad have. I was thinking about going into the Airforce, if I joined. 
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 
No this is my first math class of the term. I did not know that math 115 is different then taking math 116. I need to maintain an a C in this class for my plan on getting my associates un psychology.

   
 






  




